ppd_config = {
    'username': 'manvi.moza@pb.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360uk',
    'base_api': 'https://api-uk-ppd.shipping360.pitneybowes.com/locker',
    'badge_idp': 'https://api-uk-ppd.shipping360.pitneybowes.com/badgeidp',
    'ilp_lms': 'https://api-uk-ppd.shipping360.pitneybowes.com/ilplms',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'env': 'PPD',
    'CLIENTUSERNAME': "manviukppd@yopmail.com",
    'client_pwd': 'Aqswde@123',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/austy3sz0fTwQDobE0h7/v1/token',
    'ILP_clientID': '0oa1wfwl6atNTefw10h8',
    'ILP_secret': 'HwLYTOrG7E40IkdDy-BjagLh2FcseSR6iE2t_Q7TGO-C5aqryMFjOzqcpebVTUPY',
    'INT_clientID': '0oa1wl1ipufChl57n0h8',
    'INT_secret': 'ZnTKsdIWQjMS9CZzjgsrApg1jSfUIwJOTQbmln4FNFm3I1wL88ZeAwY-UFWOaA7o',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
    'receiving_api': 'https://api-uk-ppd.shipping360.pitneybowes.com/fireball',
    'devicehub_api': 'https://api-uk-ppd.shipping360.pitneybowes.com/devicehub',
}