ppd_config = {
    'username': 'lockerspitney@gmail.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360canada',
    'base_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/locker',
    'badge_idp': 'https://api-ppd.shipping360.pitneybowes.com/ca/badgeidp',
    'receiving_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/fireball',
    'ilp_lms': 'https://api-ppd.shipping360.pitneybowes.com/ca/ilplms',
    'devicehub_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/devicehub',
    'env': 'PPD',
    'CLIENTUSERNAME': "manvi.moza@pb.com",
    'client_pwd': 'Aqswde@123',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/aus16413gxj3InUf00h8/v1/token',
    'clientID': '0oa1p3gv314XKjxxS0h8',
    'clientSecret': 'SguOtV68IMY2SYApNuvTfx7SD6O2BTSrgCny-I9b',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
}
