dev_config = {
    'username': 'pravinbankardevenv@yopmail.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360commercial',
    'base_api': 'https://api-dev.sendpro360.pitneycloud.com/locker',
    'badge_idp': 'https://api-dev.sendpro360.pitneycloud.com/badgeidp',
    'ilp_lms': 'https://api-dev.sendpro360.pitneycloud.com/ilplms',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'env': 'DEV',
    'CLIENTUSERNAME': "pravinbankardev@yopmail.com",
    'client_pwd': 'Aqswde@123',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/austlaq2lihWmiUEP0h7/v1/token',
    'ILP_clientID': '0oa1761gji5gZLX8G0h8',
    'ILP_secret': '3qnFwmnGvLxKUeN1psYOrXB3rX1dQmuoqzDusaqK',
    'INT_clientID': '0oa1t20iiav6Ombqt0h8',
    'INT_secret': 'Xf3ICt-56VjZ7zsqYbTNKdEuf3Nd6O4VyAlzySOcLA8TZKBH0wubcdNqAapH6nFC',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
    'db_username': 'sp360user-dev',
    'db_password': 'wpbCmMKRwoDCrsKkwq7CvMKuwqrCgcKBw4DCqMKKwrs=',
    'db_connection': 'mongodb+srv://db_usr:db_pwd@sp360-commercial-global.bx3ql.mongodb.net/admin?authSource=admin&replicaSet=atlas-6dgy6p-shard-0&readPreference=primary&ssl=true',
    'receiving_api': 'https://receiving-service-dev.sendpro360.pitneycloud.com',
    'devicehub_api': 'https://api-dev.sendpro360.pitneycloud.com/devicehub',
    'notification_api': 'https://notificationsvc-dev.sendpro360.pitneycloud.com'
}

qa_config = {
    'username': 'manvi@yopmail.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360commercial',
    'base_api': 'https://api-qa.sendpro360.pitneycloud.com/locker',
    'badge_idp': 'https://api-qa.sendpro360.pitneycloud.com/badgeidp',
    'ilp_lms': 'https://api-qa.sendpro360.pitneycloud.com/ilplms',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'env': 'QA',
    'CLIENTUSERNAME': "pravinqa@yopmail.com",
    'client_pwd': 'Aqswde@123',
    'app_type': 'lockers',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/austlb7mc40Fgj6ik0h7/v1/token',
    'ILP_clientID': '0oa15th7suz1ncLCL0h8',
    'ILP_secret': '9NNy018jyplnsMuyFcz92KPK82aUnOxxDBBfrq2t',
    'INT_clientID': '0oa1p6v6r13y8gYWL0h8',
    'INT_secret': 'MPIbykh1uu9Uj3C2uc6ALIkyM2Q_WfBmDsCcgzv7',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
    'db_username': 'sp360user-dev',
    'db_password': 'wpbCmMKRwoDCrsKkwq7CvMKuwqrCgcKBw4DCqMKKwrs=',
    'db_connection': 'mongodb+srv://db_usr:db_pwd@sp360-commercial-global.bx3ql.mongodb.net/admin?authSource=admin&replicaSet=atlas-6dgy6p-shard-0&readPreference=primary&ssl=true',
    'receiving_api': 'https://receiving-service-qa.sendpro360.pitneycloud.com',
    'devicehub_api': 'https://api-qa.sendpro360.pitneycloud.com/devicehub',
    'imap_email': 'lockerspitney@gmail.com',
    # 'imap_password': 'avrlpiokfvjgimxk'
    'imap_password': 'wqjDg8KzwrXCvMKuwr3CrsK4w4_CusK7wrLCvMOGwrY=',
    'notification_api': 'https://notificationsvc-qa.sendpro360.pitneycloud.com'
}

ppd_config = {
    'username': 'manvi.moza@pb.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360commercial',
    'base_api': 'https://api-ppd.sendpro360.pitneybowes.com/locker',
    'badge_idp': 'https://api-ppd.sendpro360.pitneybowes.com/badgeidp',
    'ilp_lms': 'https://api-ppd.sendpro360.pitneybowes.com/ilplms',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'env': 'PPD',
    'CLIENTUSERNAME': "Pravinbankar1991+1@gmail.com",
    'client_pwd': 'Aqswde@123',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/ausu9vcd4qIb9JPLG0h7/v1/token',
    'ILP_clientID': '0oa16qzlqwqL0HjMB0h8',
    'ILP_secret': 'BQuG2U7p0vcNxWnOCZXDxZRfuz-gr0f7qeByv0qP',
    'INT_clientID': '0oa1su6d2bn7FIclh0h8',
    'INT_secret': 'J3msKcBUQcG2aDcpYz6L9l_BdSmrAF8mR6gauZE_lR6gh789VIOHZAoVVDQsND6d',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
    'receiving_api': 'https://api-ppd.sendpro360.pitneybowes.com/fireball',
    'devicehub_api': 'https://api-ppd.sendpro360.pitneybowes.com/devicehub',
    'notification_api': 'https://notificationsvc-qa.sendpro360.pitneycloud.com',
    'imap_email': 'lockerspitney@gmail.com',
    # 'imap_password': 'avrlpiokfvjgimxk'
    'imap_password': 'wqjDg8KzwrXCvMKuwr3CrsK4w4_CusK7wrLCvMOGwrY='
}

perf_config = {
    'username': 'manvi@yopmail.com',
    'enc_pwd': 'Aqswde@123',
    'Project': 'lockers_services',
    'product_name': 'sp360commercial',
    'base_api': 'https://api-prf.sendpro360.pitneycloud.com/locker',
    'badge_idp': 'https://api-prf.sendpro360.pitneycloud.com/badgeidp',
    'ilp_lms': 'https://api-prf.sendpro360.pitneycloud.com/ilplms',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'env': 'QA',
    'CLIENTUSERNAME': "pravinqa@yopmail.com",
    'client_pwd': 'Aqswde@123',
    'app_type': 'lockers',
    'X-PB-TransactionId': 'lockers_{unique_no}',
    'oauth_2.0': 'https://pitneybowes.oktapreview.com/oauth2/austlb7mc40Fgj6ik0h7/v1/token',
    'clientID': '0oa15th7suz1ncLCL0h8',
    'clientSecret': '9NNy018jyplnsMuyFcz92KPK82aUnOxxDBBfrq2t',
    'json_body': {"grant_type": "client_credentials", "scope": "spa"},
    'db_username': 'sp360user-dev',
    'db_password': 'wpbCmMKRwoDCrsKkwq7CvMKuwqrCgcKBw4DCqMKKwrs=',
    'db_connection': 'mongodb+srv://db_usr:db_pwd@sp360-commercial-global.bx3ql.mongodb.net/admin?authSource=admin&replicaSet=atlas-6dgy6p-shard-0&readPreference=primary&ssl=true',
    'receiving_api': 'https://receiving-service-qa.sendpro360.pitneycloud.com',
    'devicehub_api': 'https://receiving-service-qa.sendpro360.pitneycloud.com',
    'notification_api': 'https://notificationsvc-qa.sendpro360.pitneycloud.com',
    'imap_email': 'lockerspitney@gmail.com',
    # 'imap_password': 'avrlpiokfvjgimxk'
    'imap_password': 'wqjDg8KzwrXCvMKuwr3CrsK4w4_CusK7wrLCvMOGwrY='
}
