qa_config = {
    'username': 'apiadminqauser@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Test@123',
    'Project': 'shared_services',
    'product_name': 'canada',
    'env': 'QA',
    'is_admin': 'N',
    'CLIENTUSERNAME': "ca_spwelcome_115@yopmail.com",
    'client_pwd': 'Pitney@123',
    'addrbook_api': 'https://addrbook-qa.sendpro360.pitneycloud.com',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'climgmt_api': 'https://climgmt-dev.sendpro360.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-dev.sendpro360.pitneycloud.com',
    'submgmt_api': 'https://submgmt-dev.sendpro360.pitneycloud.com'
},
ppd_config = {
    'username': 'pbsp360+ca.ppd.adm1@gmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
    'Project': 'shared_services',
    'product_name': 'sp360canada',
    'env': 'PPD',
    'is_admin': 'N',
    'CLIENTUSERNAME': 'pbsp360+ca.ppd.e1@gmail.com',
    'client_pwd': 'Horizon#123',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'addrbook_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/addrbook',
    'climgmt_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/climgmt',
    'cost_acct_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/costactmgmt',
    'prodmgmt_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/prodmgmt',
    'submgmt_api': 'https://api-ppd.shipping360.pitneybowes.com/ca/submgmt'
}