dev_config = {
    'username': 'apiadminuser@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Test@1234',
    'Project': 'shared_services',
    'product_name': 'sp360commercial',
    'env': 'DEV',
    'is_admin': 'N',
    'CLIENTUSERNAME': "apiclient01@yopmail.com",
    'client_pwd': 'Test@1234',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1mvxclyu6dlE7Q0h8',
    'device_cli_secret': '_miFcVr19fGNVDpX7VRRh1YhlV3f_YRL8Z6aNZIr',
    'okta_group_id': '00gtl9eqrlc2YsVOd0h7',
    'ccbs_authorization': 'wobCo8K4wrfCpnLCqMKmwq7CkMKcwrvCr8KcwrPCm8KuwrvCs8KuwovDj8Kew4LCi8KTwrDDhcKswo7CksKGwpPCtsKWwqfCn8KjwqHCtcKRwpLCrsKwwq_Cl8KcdcKxecKgwp_CuMOIwpzCucKYw4XCqcKfwrTCqsKqwpTCmMOJwrLCqMK4wprCosK1wojCgg==',
    'db_username': 'sp360user-dev',
    'db_password': 'wpbCmMKRwoDCrsKkwq7CvMKuwqrCgcKBw4DCqMKKwrs=',
    'db_connection': 'mongodb+srv://db_usr:db_pwd@sp360-commercial-global.bx3ql.mongodb.net/admin?authSource=admin&replicaSet=atlas-6dgy6p-shard-0&readPreference=primary&ssl=true',
    'submgmt_api': 'https://submgmt-dev.sendpro360.pitneycloud.com',
    'climgmt_api': 'https://climgmt-dev.sendpro360.pitneycloud.com',
    'addrbook_api': 'https://addrbook-dev.sendpro360.pitneycloud.com',
    'subcarrieractmgmt_api': 'https://subcarrieractmgmt-dev.sendpro360.pitneycloud.com',
    'costactmgmt_api': 'https://costactmgmt-dev.sendpro360.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-dev.sendpro360.pitneycloud.com',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-dev.sendpro360.pitneycloud.com',
    'notification_api': 'https://notificationsvc-dev.sendpro360.pitneycloud.com',
    'custom_api': 'https://spa-ui-dev.sendpro360.pitneycloud.com',
    'notification_endpoint': 'https://notificationsvc-dev.sendpro360.pitneycloud.com',
    'custom_field_endpoint': 'https://submeta-dev.sendpro360.pitneycloud.com',
    'ccbs_api': 'https://api-qa.pitneybowes.com',
    'audit_logging_endpoint': 'http://audit-event-usage-service-prf.sendpro360.pitneycloud.com',
    'jit_service_api': 'https://jitprovisioning-dev.sendpro360.pitneycloud.com',
    'jit_auth': 'wobCo8K4wrfCpnLCvMKDwqrDgMKpwqbClXbCvHbCmMK-wp3CrsK6wqnCpsKawpfCmcKlwpDCtcKfwpdywr3CgMKnwpjCq8Kdwqp7woTDgsKfwprDhHnClcKMfnjCrMOGw4DCncKrwpfCmHvCqcOEwrTCisKYwrnCncOFwrDCpsOEw4DCsMKUwq7Cgg=='
}

qa_config = {
    'username': 'apiadminqauser@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Test@123',
    'Project': 'shared_services',
    'product_name': 'sp360commercial',
    'env': 'QA',
    'is_admin': 'N',
    'CLIENTUSERNAME': "api_qa_client@yopmail.com",
    'client_pwd': 'Test@123',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1mvww4p2WqQGer0h8',
    'device_cli_secret': 'SOcjwGp5q9pLYqK2J_eYHKRKXPjdmfHEV1hYt2Wh',
    'okta_group_id': '00gtl9cu6fdFr2OkH0h7',
    'ccbs_authorization': 'wobCo8K4wrfCpnLCqMKmwq7CkMKcwrvCr8KcwrPCm8KuwrvCs8KuwovDj8Kew4LCi8KTwrDDhcKswo7CksKGwpPCtsKWwqfCn8KjwqHCtcKRwpLCrsKwwq_Cl8KcdcKxecKgwp_CuMOIwpzCucKYw4XCqcKfwrTCqsKqwpTCmMOJwrLCqMK4wprCosK1wojCgg==',
    'db_username': 'sp360user-dev',
    'db_password': 'wpbCmMKRwoDCrsKkwq7CvMKuwqrCgcKBw4DCqMKKwrs=',
    'db_connection': 'mongodb+srv://db_usr:db_pwd@sp360-commercial-global.bx3ql.mongodb.net/admin?authSource=admin&replicaSet=atlas-6dgy6p-shard-0&readPreference=primary&ssl=true',
    'submgmt_api': 'https://submgmt-qa.sendpro360.pitneycloud.com',
    'climgmt_api': 'https://climgmt-qa.sendpro360.pitneycloud.com',
    'addrbook_api': 'https://addrbook-qa.sendpro360.pitneycloud.com',
    'subcarrieractmgmt_api': 'https://subcarrieractmgmt-qa.sendpro360.pitneycloud.com',
    'costactmgmt_api': 'https://costactmgmt-qa.sendpro360.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-qa.sendpro360.pitneycloud.com',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-qa.sendpro360.pitneycloud.com',
    'notification_api': 'https://notificationsvc-qa.sendpro360.pitneycloud.com',
    'custom_field_endpoint': 'https://submeta-qa.sendpro360.pitneycloud.com',
    'ccbs_api': 'https://api-qa.pitneybowes.com',
    'audit_logging_endpoint': 'http://audit-event-usage-service-qa.sendpro360.pitneycloud.com',
    'jit_service_api': 'https://jitprovisioning-qa.sendpro360.pitneycloud.com',
    'jit_auth': 'wobCo8K4wrfCpnLCvMKDwqrDgMKpwqbClXbCvHbCmMK-wp3CrsK6wqnCpsKawpfCmcKlwpDCtcKfwpdywr3CgMKnwpjCq8Kdwqp7woTDgsKfwprDhHnClcKMfnjCrMOGw4DCncKrwpfCmHvCqcOEwrTCisKYwrnCncOFwrDCpsOEw4DCsMKUwq7Cgg=='
}

perf_config = {
    'username': 'sohail.perf.admin1@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
    'Project': 'shared_services',
    'product_name': 'sp360commercial',
    'env': 'PERF',
    'is_admin': 'N',
    'CLIENTUSERNAME': "sohail.perf.cli.e1@yopmail.com",
    'client_pwd': 'Horizon#123',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1b5dg11wDOL6I30h8',
    'device_cli_secret': '_cxtObXx0_QFp2YA4jBbTfeagPCUtTgCGr8ugLAV',
    'okta_group_id': '00g102w6hm7uDXJ170h8',
    'ccbs_authorization': 'wobCo8K4wrfCpnLCqMKmwq7CkMKcwrvCr8KcwrPCm8KuwrvCs8KuwovDj8Kew4LCi8KTwrDDhcKswo7CksKGwpPCtsKWwqfCn8KjwqHCtcKRwpLCrsKwwq_Cl8KcdcKxecKgwp_CuMOIwpzCucKYw4XCqcKfwrTCqsKqwpTCmMOJwrLCqMK4wprCosK1wojCgg==',
    'login_api': 'https://login2-api-pre.saase2e.pitneybowes.com',
    'login_origin_url': 'https://login2-pre.saase2e.pitneycloud.com',
    'submgmt_api': 'https://submgmt-prf.sendpro360.pitneycloud.com',
    'climgmt_api': 'https://climgmt-prf.sendpro360.pitneycloud.com',
    'addrbook_api': 'https://addrbook-prf.sendpro360.pitneycloud.com',
    'subcarrieractmgmt_api': 'https://subcarrieractmgmt-prf.sendpro360.pitneycloud.com',
    'costactmgmt_api': 'https://costactmgmt-prf.sendpro360.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-prf.sendpro360.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-prf.sendpro360.pitneycloud.com',
    'ccbs_api': 'https://api-qa.pitneybowes.com'
}

ppd_config = {
    'username': 'sohail.ppd.admin1@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
    'Project': 'shared_services',
    'product_name': 'sp360commercial',
    'env': 'PPD',
    'is_admin': 'N',
    'CLIENTUSERNAME': "sohail.ppd.client1@yopmail.com",
    'client_pwd': 'Horizon#123',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1mvz6cjtC2Tv4F0h8',
    'device_cli_secret': 'auXcBdV0RBEOMI3ly9CpGoBWFbK0pru9Q3DvHA2C',
    'okta_group_id': '00gtl9cu6fdFr2OkH0h7',
    'ccbs_authorization': 'wobCo8K4wrfCpnLCqMKmwq7CkMKcwrvCr8KcwrPCm8KuwrvCs8KuwovDj8Kew4LCi8KTwrDDhcKswo7CksKGwpPCtsKWwqfCn8KjwqHCtcKRwpLCrsKwwq_Cl8KcdcKxecKgwp_CuMOIwpzCucKYw4XCqcKfwrTCqsKqwpTCmMOJwrLCqMK4wprCosK1wojCgg==',
    'submgmt_api': 'https://api-ppd.sendpro360.pitneybowes.com/submgmt',
    'climgmt_api': 'https://api-ppd.sendpro360.pitneybowes.com/climgmt',
    'addrbook_api': 'https://api-ppd.sendpro360.pitneybowes.com/addressbook',
    'subcarrieractmgmt_api': 'https://api-ppd.sendpro360.pitneybowes.com/subcarrieractmgmt',
    'costactmgmt_api': 'https://api-ppd.sendpro360.pitneybowes.com/costactmgmt',
    'prodmgmt_api': 'https://api-ppd.sendpro360.pitneybowes.com/prodmgmt',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-ppd.sendpro360.pitneybowes.com/enrichtoken',
    'custom_api': 'https://spa-ui-qa.sendpro360.pitneycloud.com',
    # 'notification_endpoint': 'https://notificationsvc-qa.sendpro360.pitneycloud.com',
    'custom_field_endpoint': 'https://api-ppd.sendpro360.pitneybowes.com/submetadata',
    'ccbs_api': 'https://api-qa.pitneybowes.com',
    'audit_logging_endpoint': 'http://audit-event-usage-service-ppd.sendpro360.pitneybowes.com'
}

prd_config = {
    'username': 'sohail.mohammed@pb.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'wpHCt8K2wrPCqMOGwpnCgcKGfHI=',
    'Project': 'shared_services',
    'product_name': 'sp360commercial',
    'env': 'PRD',
    'is_admin': 'N',
    'CLIENTUSERNAME': "pbsp360+prod.e1@gmail.com",
    'client_pwd': 'wozCscK3wrfCvcOBw4dzwoV7woI=',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1mvz6cjtC2Tv4F0h8',
    'device_cli_secret': 'auXcBdV0RBEOMI3ly9CpGoBWFbK0pru9Q3DvHA2C',
    'okta_group_id': '00gtl9cu6fdFr2OkH0h7',
    'ccbs_authorization': 'wobCo8K4wrfCpnLCrsKCwo3CuMKzwpXCmcKXwq7Ci3J4wq_CrsOJwozCpMKEwpPCm8KbwpDCucKMwpLCiMKfwq_ClMKqw4XCgcKofMKdwpTCrMKdwrPCjsKlwq_CtXnCpcOGwpbDhcKjwoHCnMK2wqbCscKwwrDCpsKTwrLDicKowqfDhMKiwrDCtcKIwoI=',
    'submgmt_api': 'https://api.sendpro360.pitneybowes.com/submgmt',
    'climgmt_api': 'https://api.sendpro360.pitneybowes.com/climgmt',
    'addrbook_api': 'https://api.sendpro360.pitneybowes.com/addressbook',
    'subcarrieractmgmt_api': 'https://api.sendpro360.pitneybowes.com/subcarrieractmgmt',
    'costactmgmt_api': 'https://api.sendpro360.pitneybowes.com/costactmgmt',
    'prodmgmt_api': 'https://api.sendpro360.pitneybowes.com/prodmgmt',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-ppd.sendpro360.pitneybowes.com/enrichtoken',
    'custom_api': 'https://spa-ui-qa.sendpro360.pitneycloud.com',
    # 'notification_endpoint': 'https://notificationsvc-qa.sendpro360.pitneycloud.com',
    'custom_field_endpoint': 'https://api-ppd.sendpro360.pitneybowes.com/submetadata',
    'ccbs_api': 'https://api.pitneybowes.com'
}
