dev_config = {
    'username': 'pyauto.dev.fadmin1@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Pitney@1234',
    'Project': 'shared_services',
    'product_name': 'fedramp',
    'env': 'DEV',
    'is_admin': 'Y',
    'CLIENTUSERNAME': "pyauto.dev.fuser1@yopmail.com",
    'client_pwd': 'Pitney@1234',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1bjmquvlyjo3BD0h8',
    'device_cli_secret': 'RJvoQz-oKX2fbZ0Xx9LlQrorF4m3FbI1HeW1y8OS',
    'submgmt_api': 'https://submgmt-dev.fedramp.pitneycloud.com',
    'climgmt_api': 'https://climgmt-dev.fedramp.pitneycloud.com',
    'addrbook_api': 'https://addrbook-dev.fedramp.pitneycloud.com',
    'subcarrieractmgmt_api': 'https://subcarrieractmgmt-dev.fedramp.pitneycloud.com',
    'costactmgmt_api': 'https://costactmgmt-dev.fedramp.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-dev.fedramp.pitneycloud.com',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'sso_url': 'https://sso.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-dev.fedramp.pitneycloud.com',
    'custom_field_endpoint': 'https://submeta-dev.fedramp.pitneycloud.com'
}

qa_config = {
    'username': 'pyauto.fadmin1@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Pitney@1234',
    'Project': 'shared_services',
    'product_name': 'fedramp',
    'env': 'QA',
    'is_admin': 'Y',
    'CLIENTUSERNAME': "pyauto.fuser1@yopmail.com",
    'client_pwd': 'Pitney@1234',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1bjqyyhvr3xvHX0h8',
    'device_cli_secret': 'hmrN3KDewRq2kQmP4suIll-4aPhCfnGhYa5pRNPQ',
    'submgmt_api': 'https://submgmt-qa.fedramp.pitneycloud.com',
    'climgmt_api': 'https://climgmt-qa.fedramp.pitneycloud.com',
    'addrbook_api': 'https://addrbook-qa.fedramp.pitneycloud.com',
    'subcarrieractmgmt_api': 'https://subcarrieractmgmt-qa.fedramp.pitneycloud.com',
    'costactmgmt_api': 'https://costactmgmt-qa.fedramp.pitneycloud.com',
    'prodmgmt_api': 'https://prodmgmt-qa.fedramp.pitneycloud.com',
    'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    'sso_url': 'https://sso.pitneycloud.com',
    'enrich_api': 'https://enrichtoken-qa.fedramp.pitneycloud.com',
    'custom_field_endpoint': 'https://submeta-qa.fedramp.pitneycloud.com'
}

ppd_config = {
    'username': 'pbsp360+ppd.fadmin1@gmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Pitney@123',
    'Project': 'shared_services',
    'product_name': 'fedramp',
    'env': 'PPD',
    'is_admin': 'Y',
    'CLIENTUSERNAME': "pbsp360+ppd.fe1@gmail.com",
    'client_pwd': 'Pitney@123',
    'enrich_cli_id': 'superuser',
    'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    'device_cli_id': '0oa1mvz6cjtC2Tv4F0h8',
    'device_cli_secret': 'auXcBdV0RBEOMI3ly9CpGoBWFbK0pru9Q3DvHA2C',
    'okta_group_id': '00gtl9cu6fdFr2OkH0h7',
    'submgmt_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/submgmt',
    'climgmt_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/climgmt',
    'addrbook_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/addressbook',
    'subcarrieractmgmt_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/subcarrieractmgmt',
    'costactmgmt_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/costactmgmt',
    'prodmgmt_api': 'https://api-ppd.sendpro360gov.pitneybowes.com/prodmgmt',
    'login_api': 'https://sso-ppd.sendpro360gov.pitneybowes.com/api/v1/authn',
    'login_origin_url': 'https://sso-ppd.sendpro360gov.pitneybowes.com',
    'sso_url': 'https://sso-ppd.sendpro360gov.pitneybowes.com',
    'enrich_api': 'https://enrichtoken-ppd.sendpro360gov.pitneybowes.com/enrichtoken',
    'custom_field_endpoint': 'https://api-ppd.sendpro360gov.pitneybowes.com/submetadata'
}
