getDeviceHubByUserID = "/api/v1/devicehub/userId"
getDeviceHubByLocId = "/api/v1/devicehub/locId"
print_request = "/api/v1/print"
printv2_request = "/api/v2/print"
print_scale_request = "/api/v1/scale/read"
DeleteDeviceHubBySN = "/api/v1/devicehub/sn/{sn_no}"
getDHSupportedVersion = "/api/v1/supported/version"
SubscriptionSettings = "/api/v1/subscription/setting"
Add_Devicehub = "/api/v1/devicehub"
Update_DeviceHub = "/api/v1/devicehub/sn/{serialnumber}/update"
save_coordinate = "/api/v1/instance/print-coordinate"
get_coordinate = "/api/v1/instance/print-coordinate"
hbc_printer_mapping = "/api/v1/printer/mapping"
get_hbc_printer_mapping = "/api/v1/printer/mapping?alias={alias_name}"
delete_printer_mapping = "/api/v1/printer/mapping?alias={alias_name}"
hbc_print_document = "/api/v1/document/print"
get_Transaction_Status_By_JobID ="/api/v1/jobs/{jobid}"
get_Transaction_v2_Status_By_JobID ="/api/v2/jobs/{jobid}"