dev_config = {
    'username': 'spshellautomation01@mailinator.com',
    # 'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
    'Project': 'sendtechapps_services',
     'product_name': 'sp360commercial',
    'env': 'DEV',
    # 'is_admin': 'Y',
    'CLIENTUSERNAME': "spshellautomation01@mailinator.com",
    'client_pwd': 'Horizon#123',
    # 'enrich_cli_id': 'superuser',
    # 'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    # 'device_cli_id': '0oa1bjqyyhvr3xvHX0h8',
    # 'device_cli_secret': 'hmrN3KDewRq2kQmP4suIll-4aPhCfnGhYa5pRNPQ',
    # 'submgmt_api': 'https://submgmt-qa.fedramp.pitneycloud.com',
    # 'climgmt_api': 'https://climgmt-qa.fedramp.pitneycloud.com',
    # 'addrbook_api': 'https://addrbook-qa.fedramp.pitneycloud.com',
    # 'subcarrieractmgmt_api': 'https://subcarrieractmgmt-qa.fedramp.pitneycloud.com',
    # 'costactmgmt_api': 'https://costactmgmt-qa.fedramp.pitneycloud.com',
    # 'prodmgmt_api': 'https://prodmgmt-qa.fedramp.pitneycloud.com',
    # 'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    # 'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    # 'sso_url': 'https://sso.pitneycloud.com',
    # 'enrich_api': 'https://enrichtoken-qa.fedramp.pitneycloud.com'
    'sending_legacy_api': 'https://api-qa.sendpro360.pitneycloud.com/sending-legacy'
}

qa_config = {
    'username': 'vertikacubetest16@yopmail.com',
    # 'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Pitney@123',
     'Project': 'sendtechapps_services',
    'product_name': 'sp360commercial',
    # 'product_name': 'fedramp',
    'env': 'QA',
    # 'is_admin': 'Y',
     'CLIENTUSERNAME': "vertikacubetest16@yopmail.com",
     'client_pwd': 'Pitney@123',
     'cseries_id': 'austlb7mc40Fgj6ik0h7',
     'cseries_client_id': '0oatl86njpT7nJLEX0h7',
     'cseries_scope': 'openid profile email address phone offline_access spa anx adm pbadm',
     'cseries_response_type': 'token',
     'cseries_redirect_uri': 'https://spa-ui-qa.sendpro360.pitneycloud.com/api/auth/code/callback',
     'cseries_nonce': 'NONCE55061516184315098',
     'cseries_state': '7084',
     'cseries_response_mode': 'form_post',
     'cseries_prompt': 'none',
     'cseries_sessionToken': '[tok]',
     'cseries_okta_log_in_auth_url': 'https://pitneybowes.oktapreview.com/api/v1/authn',
     'cseries_okta_preview_host': 'https://pitneybowes.oktapreview.com',
     'sending_legacy_api': 'https://api-qa.sendpro360.pitneycloud.com/sending-legacy',
     'pseries_api': 'https://spa-ps-ui-qa.sendpro360.pitneycloud.com/api'
    # 'enrich_cli_id': 'superuser',
    # 'enrich_cli_secret': 'HOTSIXJEKLvtTLWnmMI9Hm9fjHlrtvJGJFlYZphW',
    # 'device_cli_id': '0oa1bjqyyhvr3xvHX0h8',
    # 'device_cli_secret': 'hmrN3KDewRq2kQmP4suIll-4aPhCfnGhYa5pRNPQ',
    # 'submgmt_api': 'https://submgmt-qa.fedramp.pitneycloud.com',
    # 'climgmt_api': 'https://climgmt-qa.fedramp.pitneycloud.com',
    # 'addrbook_api': 'https://addrbook-qa.fedramp.pitneycloud.com',
    # 'subcarrieractmgmt_api': 'https://subcarrieractmgmt-qa.fedramp.pitneycloud.com',
    # 'costactmgmt_api': 'https://costactmgmt-qa.fedramp.pitneycloud.com',
    # 'prodmgmt_api': 'https://prodmgmt-qa.fedramp.pitneycloud.com',
    # 'login_api': 'https://login2-api-stg.saase2e.pitneycloud.com',
    # 'login_origin_url': 'https://login2-stg.saase2e.pitneycloud.com',
    # 'sso_url': 'https://sso.pitneycloud.com',
    # 'enrich_api': 'https://enrichtoken-qa.fedramp.pitneycloud.com',

}

ppd_config = {
    'username': 'psuser004@yopmail.com',
    # 'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
     'Project': 'sendtechapps_services',
     'product_name': 'sp360commercial',
    'env': 'PPD',
    # 'is_admin': 'Y',
     'CLIENTUSERNAME': "psuser004@yopmail.com",
     'client_pwd': 'Horizon#123',
     'cseries_id': 'ausu9vcd4qIb9JPLG0h7',
     'cseries_client_id': '0oau9srip3i3BYemC0h7',
     'cseries_scope': 'openid profile email address phone offline_access spa anx adm pbadm',
     'cseries_response_type': 'token id_token',
     'cseries_redirect_uri': 'http://localhost:8081/auth',
     'cseries_nonce': '875234875',
     'cseries_state': '1324',
     'cseries_response_mode': 'form_post',
     'cseries_prompt': 'none',
     'cseries_sessionToken': '[tok]',
     'cseries_okta_log_in_auth_url': 'https://pitneybowes.oktapreview.com/api/v1/authn',
     'cseries_okta_preview_host': 'https://pitneybowes.oktapreview.com',
     'sending_legacy_api': 'https://api-ppd.sendpro360.pitneybowes.com/sending-legacy'


}

