domestic_print_payload={
	"carrierProfileId": "NmyePJaj22m",
	"constructValidLastLine": False,
	"costAccountId": "mJ3pPYjQkxM",
	"costAccountName": "Triology",
	"cultureCode": "en-US",
	"customMessage": "Msg",
	"dateOfShipment": "2024-04-27T06:53:38Z",
	"dateOfShipmentTimeZone": "GMT+05:30",
	"deliveryNotificationEmails": ["", ""],
	"dimensionUnits": "IMPERIAL",
	"displayMailClass": "Priority Mail®",
	"inductionPostalCode": "14850-1242",
	"addToScanForm": False,
	"includeAndHideSuggestedTrackingService": True,
	"labelDetails": {
		"hidePostage": True,
		"printReceipt": False,
		"labelSize": "s4x6"
	},
	"labelPrintedEmailSubject": "A Shipment from P Series",
	"mailClass": "PM",
	"packageDeliveredEmailSubject": "Confirmation emails ",
	"packageDetails": {
		"girthMeters": 0.0,
		"heightMeters": 0.0,
		"lengthMeters": 0.0,
		"packageDisplayId": "FRE",
		"packageId": "FRE",
		"packageName": "Flat Rate Envelope",
		"weightKilos": 31.75144,
		"widthMeters": 0.0
	},
	"printNotificationEmails": ["", ""],
	"rateType": "COMMERCIAL",
	"recipient": {
		"city": "Las Vegas",
		"company": "Waqqas Chawre Corp",
		"email": "",
		"fullName": "William Jones",
		"militaryAddress": False,
		"residential": True,
		"verified": False,
		"isoCountry": "US",
		"phone": "1234567901",
		"postalCode": "89110-2263",
		"state": "NV",
		"streetLine1": "733 Taft Ct",
		"streetLine2": "",
		"type": "Recipient",
		"verificationStatus": "VALID",
		"version": 0
	},
	"sender": {
		"city": "Ithaca",
		"company": "",
		"fullName": "ABCD",
		"militaryAddress": False,
		"residential": False,
		"verified": False,
		"isoCountry": "US",
		"phone": "2022222222",
		"postalCode": "14850-1242",
		"state": "NY",
		"streetLine1": "730 Warren Rd",
		"streetLine2": "",
		"type": "Sender",
		"version": 0
	},
	"totalPackageCharge": "7.6",
	"weightUnits": "IMPERIAL"
}