international_print_payload={
	"carrierProfileId": "rjYwD35QD8K",
	"constructValidLastLine": False,
	"costAccountId": "pdpaWjnRYYk",
	"costAccountName": "Jamie",
	"cultureCode": "en-US",
	"customInfo": {
		"eelpfc": "NOEEI30.37A",
		"exportReason": "COMMERCIAL_SAMPLE"
	},
	"customMessage": "Msg",
	"dateOfShipment": "2024-04-27T06:53:38Z",
	"dateOfShipmentTimeZone": "GMT+05:30",
	"deliveryNotificationEmails": ["daisy.lv@pb.com", ""],
	"dimensionUnits": "IMPERIAL",
	"displayMailClass": "Priority Mail International®",
	"inductionPostalCode": "94025",
	"addToScanForm": True,
	"includeAndHideSuggestedTrackingService": True,
	"labelDetails": {
		"hidePostage": True,
		"printReceipt": False,
		"labelSize": "s8x11"
	},
	"labelPrintedEmailSubject": "A Shipment from P Series",
	"mailClass": "PMI",
	"packageContent": [{
		"description": "saasc",
		"itemWeightKilos": 0.453592,
		"originCountry": "US",
		"quantity": 1,
		"value": 1.0
	}],
	"packageDeliveredEmailSubject": "Confirmation emails ",
	"packageDetails": {
		"girthMeters": 0.0,
		"heightMeters": 0.381,
		"lengthMeters": 0.381,
		"packageDisplayId": "LP",
		"packageId": "LP",
		"packageName": "Large Package",
		"weightKilos": 13.607759999999999,
		"widthMeters": 0.381
	},
	"printNotificationEmails": ["daisy.lv@pb.com", ""],
	"rateType": "COMMERCIAL",
	"recipient": {
		"city": "Jonquière",
		"company": "",
		"email": "",
		"externalId": "63e25122a5e1fe870cb986f4",
		"fullName": "Canada address",
		"militaryAddress": False,
		"residential": False,
		"verified": False,
		"isoCountry": "CA",
		"phone": "1232312424",
		"postalCode": "G7X 9N8",
		"state": "QC",
		"streetLine1": "1-2260 Rue Chambly",
		"streetLine2": "",
		"type": "Recipient",
		"version": 0
	},
	"sender": {
		"city": "Las Vegas",
		"company": "Waqqas Chawre Corp",
		"email": "daisy.lv@pb.com",
		"externalId": "61e96eb027bfdedc7270c899",
		"fullName": "William Jones",
		"militaryAddress": False,
		"residential": True,
		"verified": True,
		"isoCountry": "US",
		"phone": "1234567901",
		"postalCode": "89110-2263",
		"state": "NV",
		"streetLine1": "733 Taft Ct",
		"streetLine2": "",
		"type": "Sender",
		"version": 0
	},
	"totalPackageCharge": "129.73",
	"weightUnits": "IMPERIAL"
}