verify_address_payload={
  "address": {
    "addressType": "RECIPIENT",
    "city": "Massapequa",
    "company": "Test Y",
    "contact": {
      "companyName": "Test Y",
      "createDate": "2022-09-15T11:53:14.106Z",
      "customerPartnerId": "",
      "fullName": "Test",
      "homePhone": "",
      "id": 1,
      "idpUserId": "00u10x3hedgcVWuun0h8",
      "archived": False,
      "shared": False,
      "mobilePhone": "",
      "modifyDate": "0001-01-01T00:00:00Z",
      "otherPhone": "",
      "primaryEmail": "",
      "primaryFax": "",
      "secondaryEmail": "",
      "secondaryFax": "",
      "simpleName": "Test",
      "version": 0,
      "workPhone": ""
    },
    "createDate": "2022-09-15T11:53:14.106Z",
    "fullName": "Test",
    "id": "6323122a6869f3f703fde4b2",
    "militaryAddress": False,
    "verified": False,
    "isoCountry": "US",
    "modifyDate": "0001-01-01T00:00:00Z",
    "phone": "",
    "postalCode": "11758",
    "state": "NY",
    "streetLine1": "7 Waterview Ave",
    "streetLine2": "",
    "streetLine3": "",
    "verificationState": "",
    "version": 100
  },
  "cultureCode": "en-US",
  "allowValidLastLine": True,
  "validatePostalCodeOnly": True,
  "originCountry": "US"
}