OnBoardShopifyStore: str = "/api/v2/register/shopify/sso"
UnregisterStore = "/api/v2/unregister/store/{storeKey}"
GetAvailableCarts = "/api/v2/carts/{country_code}/clients"
GetRegisteredCarts = "/api/v2/registeredcarts/clients"
SyncOrder = "/api/v2/orders?wh=true"
OrderStatus = "/api/v2/order/status"
GetOrderJobStatus = "/api/v2/orders/job/status/{transaction_id}"
GetOrder = "/api/v2/orders/id/{id}"
orderfullfillment = "/api/v2/shipment"
GetCountryCarts = "/api/v2/carts/{country_code}"
OnBoardMagentoStore = "/api/v2/register/magento"
GetShopifySSOURL = "/api/v2/register/shopify/sso/{store_url}"
ResgisterShopifyCallback = "/api/v2/register/shopify/sso/callback"
OnBoardMckessonStore = "/api/v2/store/register"
OrderDetailsMckessonStore = "/api/v2/store/orders"
OnBoardEpicStore = "/api/v2/store/register"