dev_config = {
    'base_uri_ecomm': 'https://ecommerce-dev.sendpro360.pitneycloud.com',
    'username': 'QA_Client@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Test#123',
    'country_code': 'US',
    'subscriptionid': 'subsciption000111',
    'subid': 'subid{unique_no}',
    'subidsaved': '{unique_no}',
    'product_name': 'sp360commercial',
    'CLIENTUSERNAME': "QA_Client@yopmail.com",
    'client_pwd': 'Test#123',
    'X-PB-TransactionId': 'ecomspe.spe.pitneybowes.com.{unique_no}',
    'expired_access_token': 'eyJraWQiOiJNTXZKOG0wLUpHdGlkanM0ZWFKb19EdnhLRGdLNE9pRC0wRjNucGNrUmhNIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjhlamJ0R0t1RWoxSTR5ZThyUDA1TlB5TjhLQ2RrclktbUkwTmk4V1dvZWMiLCJpc3MiOiJodHRwczovL3BpdG5leWJvd2VzLm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzdGxiN21jNDBGZ2o2aWswaDciLCJhdWQiOiJodHRwczovL2FwaS5waXRuZXlib3dlcy5jb20vc3AzNjBzZXJ2aWNlcyIsImlhdCI6MTYyNzUzNTA5MCwiZXhwIjoxNjI3NjIxNDkwLCJjaWQiOiIwb2F0bDg2bmpwVDduSkxFWDBoNyIsInVpZCI6IjAwdXk0OXJvaTl3bEs5SFUwMGg3Iiwic2NwIjpbIm9wZW5pZCIsImVtYWlsIiwic3BhIiwiYWRtIl0sInN1YiI6InRlc3RzcG9nX3FhX3VrMDFAbWFpbGluYXRvci5jb20iLCJncnAiOlsiaWRwLXNwYS11c2Vycy1xYSJdLCJzdmNWZXIiOiIzLjAiLCJjbGFpbV9hZG0iOnsibHZsQXQiOiJFIn0sImNsYWltX3NwYSI6eyJlbnRJRCI6InlRNU0yMVAwd3lRIiwibG9jSUQiOiJKNTRZVmR6RFdubyIsInN1YklEIjoibEwyN3g4NE9wSzEiLCJjbnRyeSI6IkdCIiwicm9sZXMiOlsiQk9PU1QwX0FETUlOIl0sInN0YXR1cyI6IkFDVElWRSIsImRpdklEIjoiUTRMVzlaRDBWZ3EiLCJsb2NsIjoiZW5fVUsifX0.KQN25yaDwfjf_lVjjAvnQcmq2nB_-MBdHmbyxaQj35Eglny6pgAwQwn8NsVhhUl_j0KHFHpX1P3qlyBzEth6-z7uDu5IZ90pbTPM1WFFs7qlblr7H80mEAb637Uuj0aTbbxHJXiVgbuXvVvOl_vXytpfv7SDYwaUaZy5DKK-f8BEo-sEfm-uOZDv3JuXw-yYgEeKNFjn-TgeVq9R9t2HqKHjCLQJQHD_0vF-LJn_4eLgRKKjJ2VdTOJjhz21Rk1sSknaQ-Gvr9AO7UDn6asBgmKGlyCbdcO_Vu9yU03w_hZBWLp6n_hpiYQ98YbgkFKLSdwRC8mzovb8HsFLPzvRQg ',
    'shopify_sso_url': 'pbteststor3.myshopify.com',
    'shopify_user_name': "bikram.singh@pb.com",
    'shopify_password': "hello@909",
    'base_uri_headers': "https://data-agent-api-dev.crescodata.com",
    'base_uri_line_items': "https://data-agent-api-dev.crescodata.com",
    'base_uri_tracking': "https://data-agent-api-dev.crescodata.com",
    'updatedAt_gt': "0001-01-01T00:00:00Z",
}

qa_config = {
    'base_uri_ecomm': 'https://ecommerce-qa.sendpro360.pitneycloud.com',
    'username': 'athiraclient01@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Horizon#123',
    'country_code': 'US',
    'product_name': 'sp360commercial',
    'subscriptionid': 'subsciption000111',
    'subid': 'subid{unique_no}',
    'subidsaved': '{unique_no}',
    'CLIENTUSERNAME': "athiraclient01@yopmail.com",
    'client_pwd': 'Horizon#123',
    'X-PB-TransactionId': 'ecomspe.spe.pitneybowes.com.{unique_no}',
    'expired_access_token': 'eyJraWQiOiJNTXZKOG0wLUpHdGlkanM0ZWFKb19EdnhLRGdLNE9pRC0wRjNucGNrUmhNIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjhlamJ0R0t1RWoxSTR5ZThyUDA1TlB5TjhLQ2RrclktbUkwTmk4V1dvZWMiLCJpc3MiOiJodHRwczovL3BpdG5leWJvd2VzLm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzdGxiN21jNDBGZ2o2aWswaDciLCJhdWQiOiJodHRwczovL2FwaS5waXRuZXlib3dlcy5jb20vc3AzNjBzZXJ2aWNlcyIsImlhdCI6MTYyNzUzNTA5MCwiZXhwIjoxNjI3NjIxNDkwLCJjaWQiOiIwb2F0bDg2bmpwVDduSkxFWDBoNyIsInVpZCI6IjAwdXk0OXJvaTl3bEs5SFUwMGg3Iiwic2NwIjpbIm9wZW5pZCIsImVtYWlsIiwic3BhIiwiYWRtIl0sInN1YiI6InRlc3RzcG9nX3FhX3VrMDFAbWFpbGluYXRvci5jb20iLCJncnAiOlsiaWRwLXNwYS11c2Vycy1xYSJdLCJzdmNWZXIiOiIzLjAiLCJjbGFpbV9hZG0iOnsibHZsQXQiOiJFIn0sImNsYWltX3NwYSI6eyJlbnRJRCI6InlRNU0yMVAwd3lRIiwibG9jSUQiOiJKNTRZVmR6RFdubyIsInN1YklEIjoibEwyN3g4NE9wSzEiLCJjbnRyeSI6IkdCIiwicm9sZXMiOlsiQk9PU1QwX0FETUlOIl0sInN0YXR1cyI6IkFDVElWRSIsImRpdklEIjoiUTRMVzlaRDBWZ3EiLCJsb2NsIjoiZW5fVUsifX0.KQN25yaDwfjf_lVjjAvnQcmq2nB_-MBdHmbyxaQj35Eglny6pgAwQwn8NsVhhUl_j0KHFHpX1P3qlyBzEth6-z7uDu5IZ90pbTPM1WFFs7qlblr7H80mEAb637Uuj0aTbbxHJXiVgbuXvVvOl_vXytpfv7SDYwaUaZy5DKK-f8BEo-sEfm-uOZDv3JuXw-yYgEeKNFjn-TgeVq9R9t2HqKHjCLQJQHD_0vF-LJn_4eLgRKKjJ2VdTOJjhz21Rk1sSknaQ-Gvr9AO7UDn6asBgmKGlyCbdcO_Vu9yU03w_hZBWLp6n_hpiYQ98YbgkFKLSdwRC8mzovb8HsFLPzvRQg ',
    'shopify_sso_url': 'pbteststor3.myshopify.com',
    'shopify_user_name': "bikram.singh@pb.com",
    'shopify_password': "hello@909",
    'base_uri_headers': "https://data-agent-api-dev.crescodata.com",
    'base_uri_line_items': "https://data-agent-api-dev.crescodata.com",
    'base_uri_tracking': "https://data-agent-api-dev.crescodata.com",
    'updatedAt_gt': "0001-01-01T00:00:00Z",

}

ppd_config = {
    'base_uri_ecomm': 'https://api-ppd.sendpro360.pitneybowes.com/ecomm',
    'username': 'ppd_client_user@yopmail.com',
    'pwd_encrypted_key': 'DBENCRYPTIONKEY',
    'enc_pwd': 'Aqswde@123',
    'country_code': 'US',
    'product_name': 'sp360commercial',
    'subscriptionid': 'subsciption000111',
    'subid': 'subid{unique_no}',
    'subidsaved': '{unique_no}',
    'CLIENTUSERNAME': "ppd_client_user@yopmail.com",
    'client_pwd': 'Aqswde@123',
    'X-PB-TransactionId': 'ecomspe.spe.pitneybowes.com.{unique_no}',
    'expired_access_token': 'eyJraWQiOiJNTXZKOG0wLUpHdGlkanM0ZWFKb19EdnhLRGdLNE9pRC0wRjNucGNrUmhNIiwiYWxnIjoiUlMyNTYifQ.eyJ2ZXIiOjEsImp0aSI6IkFULjhlamJ0R0t1RWoxSTR5ZThyUDA1TlB5TjhLQ2RrclktbUkwTmk4V1dvZWMiLCJpc3MiOiJodHRwczovL3BpdG5leWJvd2VzLm9rdGFwcmV2aWV3LmNvbS9vYXV0aDIvYXVzdGxiN21jNDBGZ2o2aWswaDciLCJhdWQiOiJodHRwczovL2FwaS5waXRuZXlib3dlcy5jb20vc3AzNjBzZXJ2aWNlcyIsImlhdCI6MTYyNzUzNTA5MCwiZXhwIjoxNjI3NjIxNDkwLCJjaWQiOiIwb2F0bDg2bmpwVDduSkxFWDBoNyIsInVpZCI6IjAwdXk0OXJvaTl3bEs5SFUwMGg3Iiwic2NwIjpbIm9wZW5pZCIsImVtYWlsIiwic3BhIiwiYWRtIl0sInN1YiI6InRlc3RzcG9nX3FhX3VrMDFAbWFpbGluYXRvci5jb20iLCJncnAiOlsiaWRwLXNwYS11c2Vycy1xYSJdLCJzdmNWZXIiOiIzLjAiLCJjbGFpbV9hZG0iOnsibHZsQXQiOiJFIn0sImNsYWltX3NwYSI6eyJlbnRJRCI6InlRNU0yMVAwd3lRIiwibG9jSUQiOiJKNTRZVmR6RFdubyIsInN1YklEIjoibEwyN3g4NE9wSzEiLCJjbnRyeSI6IkdCIiwicm9sZXMiOlsiQk9PU1QwX0FETUlOIl0sInN0YXR1cyI6IkFDVElWRSIsImRpdklEIjoiUTRMVzlaRDBWZ3EiLCJsb2NsIjoiZW5fVUsifX0.KQN25yaDwfjf_lVjjAvnQcmq2nB_-MBdHmbyxaQj35Eglny6pgAwQwn8NsVhhUl_j0KHFHpX1P3qlyBzEth6-z7uDu5IZ90pbTPM1WFFs7qlblr7H80mEAb637Uuj0aTbbxHJXiVgbuXvVvOl_vXytpfv7SDYwaUaZy5DKK-f8BEo-sEfm-uOZDv3JuXw-yYgEeKNFjn-TgeVq9R9t2HqKHjCLQJQHD_0vF-LJn_4eLgRKKjJ2VdTOJjhz21Rk1sSknaQ-Gvr9AO7UDn6asBgmKGlyCbdcO_Vu9yU03w_hZBWLp6n_hpiYQ98YbgkFKLSdwRC8mzovb8HsFLPzvRQg ',
    'shopify_sso_url': 'pbteststor3.myshopify.com',
    'shopify_user_name': "bikram.singh@pb.com",
    'shopify_password': "hello@909",
    'base_uri_headers': "https://data-agent-api-dev.crescodata.com",
    'base_uri_line_items': "https://data-agent-api-dev.crescodata.com",
    'base_uri_tracking': "https://data-agent-api-dev.crescodata.com",
    'updatedAt_gt': "0001-01-01T00:00:00Z",


}
